esphome:
  name: esp-cc1101
  friendly_name: esp-cc1101
  includes:
    - cc1101.h
  libraries:
    - SPI
    - 'SmartRC-CC1101-Driver-Lib'

esp32:
  board: esp32dev
  framework:
    type: arduino

logger:

api:
  encryption:
    key: !secret api_encryption_key

ota:
  - platform: esphome
    password: !secret ota_password

wifi:
  ssid: !secret wifi_ssid
  password: !secret wifi_password
  fast_connect: true
  power_save_mode: HIGH

  ap:
    ssid: 'Esp-Cc1101 Fallback Hotspot'
    password: !secret ap_password

captive_portal:

web_server:

sensor:
  - platform: custom
    lambda: |-
      auto my_sensor = new CC1101(
        18, // SCK
        19, // MISO
        23, // MOSI
        5, // CSN
        32, // GDO0
        200, // bandwidth_in_khz
        433.92, // freq_in_mhz
        id(transmitter) // id of remote_transmitter
      );
      App.register_component(my_sensor);
      return {my_sensor};
    sensors:
      id: transciver
      internal: true

remote_transmitter:
  - id: transmitter
    pin:
      number: 32 # This is GDO0
      allow_other_uses: true
    carrier_duty_percent: 100%

remote_receiver:
  - id: receiver
    pin:
      number: 32 # This is GDO0
      allow_other_uses: true
    tolerance: 50%

packages:
  left: !include left-fan/package.yaml
  right: !include right-fan/package.yaml

  # TODO:
  # - decide about the wind, direction and timers buttons - keep as buttons or expose differently?
